### ISSUE TITLE
Cannot read that as a ZipFile

### ISSUE THREAD

**Issue by johnnyshut** [Nivanchenko/IE_2023_MK_DEMO#1]
![image](https://github.com/Nivanchenko/IE_2023_MK_DEMO/assets/42472223/5b821d7a-15d3-4808-87e4-d05535f7eeb4)
Ошибка при передачи отчета об ошибках из 1С

ИНФОРМАЦИЯ - Сервера запущен и доступен на http://localhost:3333
ОШИБКА - {Модуль C:\Users\karlo\Desktop\IE_2023_MK_DEMO-master\controls\ОбработчикОтчетов.os / Ошибка в строке: 19 / Внешнее исключение (Ionic.Zip.ZipException): Cannot read that as a ZipFile}

**Comment by johnnyshut** [comment]
Подскажите, что я пропустил?

**Comment by johnnyshut** [comment]
1С:Предприятие 8.3 (8.3.23.1865)
Без пользователя
Файловый (без сжатия)
Тонкий клиент
![image](https://github.com/Nivanchenko/IE_2023_MK_DEMO/assets/42472223/16af29e1-fa13-4b1a-83f9-0f55bf1f5af4)
Режим совместимости - Версия 8.3.12

**Comment by johnnyshut** [comment]
Конфигурация не пустая, по этому когда удалил все объекты из нее - то заработало

**Comment by nixel2007** [comment]
Удивляет такое большое количество ошибок на первом скрине. На что ругается?

**Comment by johnnyshut** [comment]
Опытным путем выяснено следующее, это не совсем пустая конфа, а для экспериментов. в ней есть подсистема у которой в свойствах указана общая картирнка (png), и если картинку удалить из свойства, то все работает

**Comment by johnnyshut** [comment]
> Удивляет такое большое количество ошибок на первом скрине. На что ругается?

Там одна ошибка, ОШИБКА - {Модуль C:\Users\karlo\Desktop\IE_2023_MK_DEMO-master\controls\ОбработчикОтчетов.os / Ошибка в строке: 19 / Внешнее исключение (Ionic.Zip.ZipException): Cannot read that as a ZipFile}

то, что в модуле подчеркивается, это spell cheker
![image](https://github.com/Nivanchenko/IE_2023_MK_DEMO/assets/42472223/69c7e9d0-e0ea-473e-a8e3-08ade9474e94)

**Comment by johnnyshut** [comment]
![image](https://github.com/Nivanchenko/IE_2023_MK_DEMO/assets/42472223/59774f87-f416-4f40-839e-398f6576f256)
Сохранил эти двоичные данные. Не знаю как открыть, zip не хочет, ничего не хочет, только блокнотом нашел кое что примичательное. в ДД передается судя по всему скрин, рабочей области, по этому картинка у подсистемы влияет

**Comment by johnnyshut** [comment]
![image](https://github.com/Nivanchenko/IE_2023_MK_DEMO/assets/42472223/4a5a6818-2b1f-468a-8a6f-f7a6de780adf)
Ошибка исчезла после установки ЗадержкаПередЧтениемСокета = 1200.
Спасибо @Nivanchenko
